In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('news.csv' , index_col=0)

In [3]:
df

,title,text,label
8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [5]:
df['content'] = df['title'] + "  " + df['text']
df = df.drop(columns = ['title' , 'text'])

In [6]:
df

      label                                            content
8476   FAKE  You Can Smell Hillary’s Fear  Daniel Greenfiel...
10294  FAKE  Watch The Exact Moment Paul Ryan Committed Pol...
3608   REAL  Kerry to go to Paris in gesture of sympathy  U...
10142  FAKE  Bernie supporters on Twitter erupt in anger ag...
875    REAL  The Battle of New York: Why This Primary Matte...
...     ...                                                ...
4490   REAL  State Department says it can't find emails fro...
8062   FAKE  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
8622   FAKE  Anti-Trump Protesters Are Tools of the Oligarc...
4021   REAL  In Ethiopia, Obama seeks progress on peace, se...
4330   REAL  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[6335 rows x 2 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
encoder = LabelEncoder()

In [9]:
df['label'] = encoder.fit_transform(df['label'])

In [10]:
df

       label                                            content
8476       0  You Can Smell Hillary’s Fear  Daniel Greenfiel...
10294      0  Watch The Exact Moment Paul Ryan Committed Pol...
3608       1  Kerry to go to Paris in gesture of sympathy  U...
10142      0  Bernie supporters on Twitter erupt in anger ag...
875        1  The Battle of New York: Why This Primary Matte...
...      ...                                                ...
4490       1  State Department says it can't find emails fro...
8062       0  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
8622       0  Anti-Trump Protesters Are Tools of the Oligarc...
4021       1  In Ethiopia, Obama seeks progress on peace, se...
4330       1  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[6335 rows x 2 columns]

In [11]:
df['content'] = df['content'].apply(lambda x : x.lower())

In [12]:
import string

In [13]:
def remove_punc(txt):
    return txt.translate(str.maketrans('' , '' , string.punctuation))

In [14]:
df['content'] = df['content'].apply(remove_punc)

In [15]:
def remove_num(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

In [16]:
df['content'] = df['content'].apply(remove_num)

In [17]:
df

       label                                            content
8476       0  you can smell hillary’s fear  daniel greenfiel...
10294      0  watch the exact moment paul ryan committed pol...
3608       1  kerry to go to paris in gesture of sympathy  u...
10142      0  bernie supporters on twitter erupt in anger ag...
875        1  the battle of new york why this primary matter...
...      ...                                                ...
4490       1  state department says it cant find emails from...
8062       0  the ‘p’ in pbs should stand for ‘plutocratic’ ...
8622       0  antitrump protesters are tools of the oligarch...
4021       1  in ethiopia obama seeks progress on peace secu...
4330       1  jeb bush is suddenly attacking trump heres why...

[6335 rows x 2 columns]

In [18]:
import nltk

In [19]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [20]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [21]:
stop_words = set(stopwords.words('english'))

In [22]:
def remove_stop(txt):
    words = word_tokenize(txt)
    cleaned_txt = []
    for i in words:
        if not i in stop_words:
            cleaned_txt.append(i)
    return ' '.join(cleaned_txt)

In [23]:
df['content'] = df['content'].apply(remove_stop)

In [24]:
df

       label                                            content
8476       0  smell hillary ’ fear daniel greenfield shillma...
10294      0  watch exact moment paul ryan committed politic...
3608       1  kerry go paris gesture sympathy us secretary s...
10142      0  bernie supporters twitter erupt anger dnc trie...
875        1  battle new york primary matters primary day ne...
...      ...                                                ...
4490       1  state department says cant find emails clinton...
8062       0  ‘ p ’ pbs stand ‘ plutocratic ’ ‘ pentagon ’ ‘...
8622       0  antitrump protesters tools oligarchy informati...
4021       1  ethiopia obama seeks progress peace security e...
4330       1  jeb bush suddenly attacking trump heres matter...

[6335 rows x 2 columns]

In [25]:
X = df['content']

In [26]:
y = df['label']

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.20 , random_state = 42)

## Using Bag of words Vectorizer and Naive Bias

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [30]:
bow_vectorizer = CountVectorizer()

In [31]:
X_train_bow = bow_vectorizer.fit_transform(X_train)

In [32]:
X_test_bow = bow_vectorizer.transform(X_test)

In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
model_nb = MultinomialNB()

In [35]:
model_nb.fit(X_train_bow , y_train)

MultinomialNB()

In [36]:
y_pred_nb = model_nb.predict(X_test_bow)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_pred_nb , y_test)

0.8981846882399369

## Using Bag of Words Vectorizer and Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
model_LR = LogisticRegression()

In [41]:
model_LR.fit(X_train_bow , y_train)

LogisticRegression()

In [42]:
y_pred_LR = model_LR.predict(X_test_bow)

In [43]:
accuracy_score(y_pred_LR , y_test)

0.9289660615627466

## Using TFID Vectorizer and Naive Bias

In [44]:
tf_vectorizer = TfidfVectorizer()

In [45]:
X_train_tf = tf_vectorizer.fit_transform(X_train)
X_test_tf = tf_vectorizer.transform(X_test)

In [46]:
model_nb2 = MultinomialNB()

In [47]:
model_nb2.fit(X_train_tf , y_train)

MultinomialNB()

In [48]:
y_pred_nb2 = model_nb2.predict(X_test_tf)

In [49]:
accuracy_score(y_pred_nb2 , y_test)

0.8366219415943172

## Using TFID Vectorizer and Logistic Regression

In [50]:
model_LR2 = LogisticRegression()

In [51]:
model_LR2.fit(X_train_tf , y_train)

LogisticRegression()

In [52]:
y_pred_LR2 = model_LR2.predict(X_test_tf)

In [53]:
accuracy_score(y_pred_LR2 , y_test)

0.9210734017363852

## Model with heighest accuracy

In [54]:
import joblib

In [55]:
joblib.dump(model_LR , "NLP_newsprediction_model.joblib")

['NLP_newsprediction_model.joblib']

In [56]:
joblib.dump(bow_vectorizer , "NLP_newsprediction_vectorizer.joblib")

['NLP_newsprediction_vectorizer.joblib']

In [57]:
sample = df[df["label"] == 1].sample(1, random_state=42).iloc[0]

print(sample["content"][:500])

X = bow_vectorizer.transform([sample["content"]])

print(model_LR.predict(X))
print(model_LR.predict_proba(X))

going back future cnn among nascent field contenders represents future half americans hillary clinton asked new cnnorc poll whether seven possible candidates better represent future past said clinton evoked future said candidate contrast joe biden jeb bush whose names political conversation even longer clintons seen representing past americans even relative newcomers national politics closely linked past future half said new jersey gov chris christie represents past said represents future kentuc
[1]
[[5.30244959e-10 9.99999999e-01]]

In [58]:
print("rbi:", bow_vectorizer.vocabulary_.get("rbi"))
print("repo:", bow_vectorizer.vocabulary_.get("repo"))
print("mpc:", bow_vectorizer.vocabulary_.get("mpc"))
print("trump:", bow_vectorizer.vocabulary_.get("trump"))
print("clinton:", bow_vectorizer.vocabulary_.get("clinton"))

rbi: 51300
repo: None
mpc: None
trump: 65027
clinton: 11223

In [59]:
headline = "Senate Committee Advances Bipartisan Infrastructure Funding Bill"      # same headline
news = """ WASHINGTON — A bipartisan Senate committee voted Thursday to advance a major infrastructure funding bill aimed at improving highways, bridges, airports, and broadband access across the United States. Lawmakers from both parties described the legislation as a compromise after weeks of negotiations over spending levels and project priorities.

The proposal would authorize billions of dollars for transportation upgrades over the next five years while increasing oversight of federal infrastructure grants. Supporters argued that modernizing aging infrastructure would strengthen economic growth, improve public safety, and create thousands of construction jobs nationwide. """

text = headline + " " + news

X = bow_vectorizer.transform([text])

print(model_LR.predict(X))
print(model_LR.predict_proba(X))

[1]
[[0.15344146 0.84655854]]